name: switchScript

on:
  push:
    branches:
      - main
    paths:
      - 'description.txt'
      - 'diy_package.sh'
      - '.github/workflows/switchScript.yaml'
  # schedule:
  #   - cron: 0 8 * * *

env:
  SCRIPT_SH: diy_package.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt install -y jq

    - name: "Build & Release"
      run: |
        tag_name=$(date +%Y%m%d)
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "tag_name=$tag_name" >> $GITHUB_ENV
        echo "atmosphere_version=$(curl -sL https://api.github.com/repos/Atmosphere-NX/Atmosphere/releases/latest|grep 'tag_name'|awk -F ': ' '{print$2}'|sed 's/"//g'|sed 's/,//g')">> $GITHUB_ENV
        chmod +x $SCRIPT_SH
        ./$SCRIPT_SH
        zip -rq SwitchSD_$tag_name.zip SwitchSD

    - name: Read description.txt
      id: description
      uses: juliangruber/read-file-action@v1
      with:
        path: ./description.txt

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.tag_name }} ❤️ | 大气层${{ env.atmosphere_version }}个人整合包
        allowUpdates: true
        tag: ${{ env.tag_name }}
        commit: main
        token: ${{ secrets.actions_release }}
        body: "${{ steps.description.outputs.content }}"
        artifacts: "SwitchSD_${{ env.tag_name }}.zip"

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.3.2
      with:
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.actions_release }}

    - name: Delete workflow runs for current repo
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.actions_release }}
        repository: ${{ github.repository }}
        retain_days: 7
        keep_minimum_runs: 6